### ISSUE TITLE
ReactorStub hangs on streaming calls when used with an in-process-channel

### ISSUE THREAD

**Issue by mjduijn** [salesforce/reactive-grpc#128]
On a streaming return, the ReactorStub seems to get stuck when using an in-process-channel in test code.

I used the following code to setup the server, channel and stub

    @Rule
    public final GrpcCleanupRule grpcCleanup = new GrpcCleanupRule();

    grpcCleanup.register(InProcessServerBuilder
        .forName(serverName)
        .directExecutor()
        .addService(serverServiceDefinition)
        .build()
        .start()
    );

    reactorStub = ReactorPublicTradeServiceGrpc.newReactorStub(
        grpcCleanup.register(InProcessChannelBuilder.forName(serverName)
            .directExecutor()
            .build())
    );

The BlockingStub equivalent with the same setup does seem to work correctly

**Comment by rmichela** [comment]
What kind of operation are you testing? one to one, many to one?

**Comment by mjduijn** [comment]
One to many

**Comment by rmichela** [comment]
Short-term: try removing `directExecutor()`.
Long-term: looking into it.

**Comment by mjduijn** [comment]
Thanks!
