### ISSUE TITLE
(rxgrpc) Splitting a stream into first and rest cancels the whole stream when first is consumed

### ISSUE THREAD

**Issue by ehiggs** [salesforce/reactive-grpc#131]
If you try to split a stream in rx grpc into first (e.g. `firstOrError`) and rest (e.g. `skip(1)`, then consuming the `first` stream cancels the rest of the stream which results in the whole result being cancelled. This appears to be hidden at first because testing using `Flowable<?>.just(...)` still pump data through quickly, [but there is a timeout on the cancellation after 100ms](https://github.com/salesforce/reactive-grpc/blob/master/common/reactive-grpc-common/src/main/java/com/salesforce/reactivegrpc/common/ReactiveStreamObserverPublisherServer.java#L48).

Example failing code:
```java
@Override
public Single<HelloResponse> sayHelloReqStream(Flowable<HelloRequest> rxRequest) {
    Single<HelloRequest> first = rxRequest.firstOrError();
    Flowable<HelloRequest> rest = rxRequest.skip(0);
    return first
        .flatMap(firstVal -> {
           return rest
            .map(HelloRequest::getName)
            .toList()
            .map(names -> {
                ArrayList<String> strings = Lists.newArrayList(firstVal.getName());
                strings.addAll(names);
                Thread.sleep(1000);
                return greet("Hello", String.join(" and ", strings));
            });
        });
}
```

Another approach using ConnectableFlowable that fails for the same reason:

```java
@Override
public Single<HelloResponse> sayHelloReqStream(Flowable<HelloRequest> rxRequest) {
  ConnectableFlowable<HelloRequest> cf = rxRequest.publish();
  Single<HelloResponse> hello = cf.firstOrError()
      .flatMap(firstVal -> {
        return cf
            .map(HelloRequest::getName)
            .toList()
            .map(names -> {
              ArrayList<String> strings = Lists.newArrayList(firstVal.getName());
              strings.addAll(names);
              Thread.sleep(1000);
              return greet("Hello", String.join(" and ", strings));
            });
      });
  cf.connect();
  return hello;
}
```

Expected: This should just work, afaics.

**Comment by rmichela** [comment]
Will take a look soon. Life is a bit intense right now. 😕

**Comment by OlegDokuka** [comment]
@ehiggs you can do that with the [`.switchOnFirst`](https://github.com/salesforce/reactive-grpc/pull/138/files#diff-6c5dd7889116a9cd8995bba777a61f74R26) operator which allows you to handle the first signal and transform the whole stream then. See #136.

**Comment by rmichela** [comment]
Digging in. RxGrpc looks like it is working correctly. The `Single` you are returning from your service method passes through `firstOrError()`. This method returns a `Single` that [explicitly cancels](https://github.com/ReactiveX/RxJava/blob/579e90dc21937b900877a8baf3918cdca22d3a91/src/main/java/io/reactivex/internal/operators/flowable/FlowableElementAtSingle.java#L83-L88) the upstream pipeline as soon as the first element is consumed.

Below its abstractions, gRPC treats all service requests as a full-duplex pair of streams. Unary requests and responses just add a singleton-message constraint to their respective streams. When one stream is canceled, so is the other. When your service method cancels the request stream after consuming the first message in `firstOrError()`, the response stream is closed before messages can be returned.

**Comment by rmichela** [comment]
You can use the [`publish(selector)`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#publish-io.reactivex.functions.Function-) operator to achieve what you want.
