### ISSUE TITLE
Compose operator usage for RxJava2 implementation

### ISSUE THREAD

**Issue by TaxistSamael** [salesforce/reactive-grpc#134]
Hi, 

First of all, my team and I are really appreceate for the tool you made. 

In RxJava part of reactive-grpc documentation I saw following:

> Used on their own, the generated RxGrpc stub methods do not cleanly chain with other RxJava operators. Using the compose() and as() methods of Single and Flowable are preferred over direct invocation.

Could you please explain, what do you mean by 'stub methods do not clearly chain' ?

**Comment by rmichela** [comment]
Idiomatic Rx chains pipelines like `source.transformation().transformation().transformation().subscribe()`, but you cannot add new transformations directly to the `Flowable` base class.

The `compose()` and `as()` transformations of `Flowable` allow you to use arbitrary functions as `Flowable` transformations by passing them in as a parameter. The `compose()` and `as()` transformations dovetail nicely with generated reactive stubs to allow expressions like `source.as(stub::doThis).as(stub::doThat).subscribe()`.

You can still directly invoke `stub.doThis()` directly if that makes more sense for you.
