### ISSUE TITLE
Demo Application is failing

### ISSUE THREAD

**Issue by rafaeling** [salesforce/reactive-grpc#135]
Hi,

I get this error, thus the generator doesnt generates any files.
```
--rxgrpc_out: protoc-gen-rxgrpc: %1 is not a valid Win32 application.
```
The only way to make it compile is by commenting out this line
https://github.com/salesforce/reactive-grpc/blob/4c273779c036ff19bb0220e05a4bdce64686aa12/demos/reactive-grpc-chat/rxjava-chat-android/app/build.gradle#L35

Any clue?
Thanks :)

**Comment by rmichela** [comment]
At this time, RxGrpc with Gradle only supports bash-based environments. Windows users will need to build using Windows Subsystem for Linux (win 10), Gitbash, or Cygwin.

The underlying issue is with how protobuf-gradle-plugin handles java-based protobuf plugins.

**Comment by cbornet** [comment]
Workaround : create a task that will use the maven wrapper to generate the code. Example : https://github.com/cbornet/generator-jhipster-grpc/blob/master/generators/app/templates/_grpc.gradle

**Comment by frankbenoit** [comment]
Using Win7.
I try to run the gradle build in git-bash with no success.

Next I tried to copy the snippet from @cbornet to the end of the build.gradle.
Now running from windows cmd
````
gradlew build --rerun-tasks
````

Still same error.
Any hint?
