### ISSUE TITLE
Any interest in C# versions?

### ISSUE THREAD

**Issue by gengle** [salesforce/reactive-grpc#143]
I'd be interested in kicking this off -- if it's not a fit here, I could fork and credit.  I'd like to make sure wire formats remain compatible though.

**Comment by rmichela** [comment]
The wire format is just gRPC, so everything should work fine. Reactive-gRPC just converts between the RxJava and gRPC messaging patterns in memory. Marrying up gRPC-C# with .Net Reactive Extensions would be an amazing contribution.

I'm happy to discuss further implementation details.
