### ISSUE TITLE
Bazel integration

### ISSUE THREAD

**Issue by mjduijn** [salesforce/reactive-grpc#164]
I was wondering if you would be interested in enabling [Bazel](https://bazel.build/) users to easily use the reactive-grpc plugin. 

Adding the integration would mean creating a workspace, importing dependencies using Bazel and writing a rule for generating reactive-grpc code from protos.
As a result, Bazel users will be able to import the logic from this repository instead of having to manage their own implementation.

I would be more than happy to write this logic myself and help maintain it.

**Comment by rmichela** [comment]
Sure. I'd love the PR. I don't have the expertise myself to write the Bazel integration from scratch, but I have used Bazel in other projects.

**Comment by mjduijn** [comment]
Alright! I'll experiment a little and create a PR when I have something I'm satisfied with.

**Comment by rmichela** [comment]
@mjduijn Any progress on bazel for reactive-grpc? 😄

**Comment by mjduijn** [comment]
Yes! I have an unpolished version locally but I have delayed submitting a PR until a decision is made in grpc/grpc-java#5621. Since that seems stalled, I'll submit one next week (currently on vacation w/o computer)

The reason for choosing to delay is that the reactive rules depend on the gRPC java rules. Currently these don't support import paths that are not the path to the .proto file from the repository root. This might cause friction when migrating a project (such as the examples in this repository).

**Comment by rmichela** [comment]
No worries. No hurry. 😃
