### ISSUE TITLE
Explain how metadata can be accessed at the server side

### ISSUE THREAD

**Issue by derolf** [salesforce/reactive-grpc#165]
Using the reactor version with Kotlin, a simple example how to get access to the metadata (headers) is possible inside the service call.

**Comment by derolf** [comment]
Is it correct just to use io.grpc.Context like in:

https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/ContextPropagationIntegrationTest.java

**Comment by cbornet** [comment]
Yes that's the way to do it. In the server interceptor, get the value from Metadata then put it in Context.

**Comment by rmichela** [comment]
@derolf Were we able to answer your question? If not, please re-open this issue. 😁

**Comment by derolf** [comment]
As said, putting a paragraph in the docs would be nice...

**Comment by cbornet** [comment]
Oh, and you need to put the gRPC context in the Reactive sequence context !
As said by @rmichela this is the same as #54
