### ISSUE TITLE
GRPC deadline context propagation 

### ISSUE THREAD

**Issue by naveentammineni** [salesforce/reactive-grpc#176]
Hi Guys,

We have a use case where we are trying to cancel the grpc server side operations when the deadline is past. Here is our code snippet for server side

*Server side snippet*

	public Flux<CoinInfo> findCoinDetailsForMultipleSymbols(List<String> coinSymbols) {

	    return Flux.fromIterable(coinSymbols)
	        .filter(x -> {
	          if(Context.current().isCancelled()) {
	            log.info("deadline exceeded at coin: "+ x);
	            return false;
	          } else {
	            return true;
	          }
	        })
	        .doOnNext(s -> log.info("Processing coin: "+ s))
	        .flatMap(cryptoCoinsDataLoader::getCoinDetails)
	        .doOnNext(coinInfo -> log.info("returning " + coinInfo));
	}

*Client side snippet*

	public Iterator<CoinInfo> getMultipleCoinDetails(List<String> symbols) {
	    try {
	      CryptoCoinsServiceBlockingStub blockingStubWithDeadline = CryptoCoinsServiceGrpc
	          .newBlockingStub(managedChannel);
	      CoinSymbols coinSymbols = CoinSymbols.newBuilder().addAllNames(symbols).build();

	      return blockingStubWithDeadline.withDeadline(Deadline.after(300, TimeUnit.MILLISECONDS))
	          .getMultipleCoinsPrice(coinSymbols);

	    } catch(StatusRuntimeException e) {
	      if(e.getStatus() == Status.DEADLINE_EXCEEDED) {
	        log.info("Deadline has been exceeded. We dont want the response");
	      } else {
	        e.printStackTrace();
	      }
	      return null;
	    }

	}

On the server side, however smaller deadline we set, We are never getting to "deadline exceeded at coin" stmt. But on the client side we are seeing the deadline exceeded exception. Is this the right way to look at the context or am i missing something?
Here is the entire code for your reference: https://github.com/naveentammineni/reactive-grpc-example

**Comment by pluttrell** [comment]
@OlegDokuka Wondering if you might have any ideas on this. Thanks!

**Comment by rmichela** [comment]
I'll take a look as soon as I can. I'm in the middle of moving cross country.

**Comment by rmichela** [comment]
@naveenreddykarri Spring reactor and gRPC context propagation are a little funny and not fully documented in Reactive-gRPC. Do the links in #56 help?

**Comment by naveentammineni** [comment]
Thank you @rmichela. That helps!

**Comment by rmichela** [comment]
Would you mind posting the code that you got working? I'd like to use it to help document #56.

**Comment by naveentammineni** [comment]
I am passing the deadline to the subscriber context in my GrpcService like this:

`    multipleCoinsRequest
              .flatMapMany(
                  request -> coinsService.findCoinDetailsForMultipleSymbols(request.getNamesList()))
              .subscriberContext(ctx -> ctx.put("deadline", Context.current()))
              .doOnTerminate( () -> log.info("Took {} ms", (System.nanoTime() - startNanos)/(1000*1000)))
              .doOnCancel(()->log.info("cancelled the stream.."));
`

and inside my service layer, i am accessing the deadline from subscriber context as follows:
`
public Flux<CoinInfo> findCoinDetailsForMultipleSymbols(List<String> coinSymbols) {

    return Flux.fromIterable(coinSymbols)
        .flatMap((coinSymbol) -> Mono.subscriberContext()
            .flatMap(ctx -> {
              Context deadlineContext = ctx.get("deadline");
              if (deadlineContext.isCancelled()) {
                log.info("Throwing deadline exceeded exception...");
                throw new DeadlineExceededException();
              } else {
                return cryptoCoinsDataLoader.getCoinDetails(coinSymbol);
              }
            }));
  }`

I have updated this code in my [example project](https://github.com/naveentammineni/reactive-grpc-example) that i shared earlier

**Comment by rmichela** [comment]
It's not a great user experience, but it works. 😕 Flux and contexts just don't play that well together. Thanks for following up. 🙏
