### ISSUE TITLE
Status CANCELLED under load

### ISSUE THREAD

**Issue by grigorryev** [salesforce/reactive-grpc#179]
Hi,

I have a service that communicates with upstream via reactive-grpc. It performs both unary calls and subscriptions.

Under high load, after request/subscriptions rate exceeds some threshold, the service starts receiving `StatusRuntimeException`s with status `CANCELLED`.

I performed some Wireshark investigations and discovered that the amount of time taken by the service to respond to http2 PING sent by the upstream gradually increases with the load. At the moment it exceeds keepalive timeout configured for the upstream, the upstream cancels the connection.

Are there any ways to configure/examine the process of http2 ping-pong under reactive-grpc? What aspects of configuration may affect this process? What code is responsible for this processing? Where should I put a breakpoint? Any explanations, suggestions and considerations are welcome.

I'm not sure what particular information about my configuration I should provide, but I will provide anything required.

Thank you!

**Comment by rmichela** [comment]
Reactive-gRPC generated code calls down to the stock gRPC stub APIs like `StreamObserver`. Reactive-gRPC doesn't have anything to do with gRPC's HTTP/2 implementation directly.

Try replicating your conditions with a traditional gRPC client and server implementation. That should give some clarity to the source of your latency problem.
