### ISSUE TITLE
Recommended Scheduler Implementations

### ISSUE THREAD

**Issue by pluttrell** [salesforce/reactive-grpc#180]
What's the recommended way to define different schedulers, if any, for the following use cases? In specific:
1. Which scheduler should we use?
2. Should we use `publishOn` or `subscribeOn`?
3. Where should we place either?

### Use Case 1: A Server that retrieves data from an Async DB (such as [Async DynamoDB](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html), that uses Netty under the covers)?

Consider the following three layers:

_gRPC Request Handler_
```java
class CarGrpcService extends ReactorCarServiceGrpc.CarServiceImplBase {

  @Override
  public Mono<Car> findCar(Mono<CarRequest> request) {

    return
      request
        .flatMap(request -> carService.findCar(request.getCarId()))
        .switchIfEmpty(Mono.error(Status.NOT_FOUND.asRuntimeException()));

  }

}
```

_Service Layer_
```java
class CarService {

  Car findCar(String id){
    
    return 
      carRepo
        .findById(id)
        .map(CarService::entityToDomain);

  }

}
```

_Repo Layer_
```java
class CarRepo {

  Mono<CarEntity> findById(String id) {

    return
      Mono
        .defer(() -> Mono.fromFuture(dynamoDbAsyncClient.getItem(buildGetItemRequest(id))))
        .filter(getItemResponse -> getItemResponse.item().size() > 0)
        .map(GetItemResponse::item)
        .map(CarRepo::buildCar);

  }

}
```

Without any scheduler definition, I see that subscriptions are happening on threads named similar to `grpc-default-executor-0` and everything after the `fromFuture` call on threads named similar to `sdk-async-response-0-2`.

### Use Case 2: Rest Controller that uses a Reactive gRPC Stub?

Consider the following app that consumes a gRPC service via the stub:

_Rest Controller_
```java
@RestController
class RegistrationController {

  @PostMapping( ... )
  Mono<Car> register(...) {

    return
      registrationService
        .register(request.getCarId(), request.getOwnerId());

  }
```

_Service Layer_
```java
class RegistrationService {

  Mono<Car> register(String carId, String ownerId){

    return
      Mono.zip(
        reactorCarServiceStub.findCar(carId),
        reactorOwnerServiceStub.findOwner(ownerId),
        (car,owner) -> { ..some logic.. }
      );
  }

}
```

**Comment by cbornet** [comment]
Use Case 1 : The `grpc-default-executor` threads you see are the ones from the default [CachedThreadPool](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newCachedThreadPool-java.util.concurrent.ThreadFactory-) used by gRPC. It's a thread-pool that will reuse threads and spawn new ones if more concurrency is needed. So it can be used with blocking code. If you're handler code is fully non-blocking you could change it to a FixedThreadPool sized at the number of CPUs.
The `sdk-async-response` threads you see are the ones used by `dynamoDbAsyncClient` to return you a CompletableFuture. You should check your AWS SDK doc to see what type of thread pool is used there.

**Comment by cbornet** [comment]
Use case 2: again gRPC ManagedChannels are configured by default with a CachedThreadPool. If you only use reactive or async stubs (never blocking stub) then it should be safe to change it by a FixedThreadPool.
If you have 2 managed channels, each will use its own thread pool and WebFlux (I assume you use WebFlux, right ?) will use another one. I guess as a small optimization, the 2 channels could use the same executor/thread pool. If the 2 stubs are on the same channel then they share the executor.

**Comment by cbornet** [comment]
And something to be aware about: https://grpc.github.io/grpc-java/javadoc/io/grpc/package-summary.html

> Both Clients and Servers should use a custom Executor. The gRPC runtime includes a default executor that eases testing and examples, but is not ideal for use in a production environment. See the associated documentation in the respective builders.
