### ISSUE TITLE
[reactor-grpc] Returning empty Mono blocks indefinitely

### ISSUE THREAD

**Issue by krakowski** [salesforce/reactive-grpc#181]
Description
--

Whenever an empty Mono is returned from an `unary → unary`/`stream → unary` call, the client blocks indefinitely. This seems to be happening because no [`completeConsumer`](https://github.com/reactor/reactor-core/blob/d0547643770260bb2bad8a58067c2f6199b38b0e/reactor-core/src/main/java/reactor/core/publisher/Mono.java#L3834) is provided within [`ServerCalls::oneToOne`](https://github.com/salesforce/reactive-grpc/blob/2b571218655674450ddd0b45af38b5bb0afd0915/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ServerCalls.java#L41-L50) and [`ServerCalls::manyToOne`](https://github.com/salesforce/reactive-grpc/blob/2b571218655674450ddd0b45af38b5bb0afd0915/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ServerCalls.java#L86-L101).

Example
--

`search_service.proto`
```protobuf
service SearchService {
    rpc search(SearchRequest) returns (Product);
}

message SearchRequest {
    int32 id = 1;
}

message Product {
    int32 id = 1;
    string name = 2;
}
```

`Server.java`
```java
public Mono<Product> search(Mono<SearchRequest> request) {
    return Mono.empty();
}
```

`Client.java`
```java
stub.search(SearchRequest.getDefaultInstance()).block();
```

Related
--
#74

**Comment by rmichela** [comment]
Great catch! 

There should be a guard around the server response Mono to ensure it returns one element, or an error. While it is legal in reactive streams to have a Mono of zero elements, gRPC unary operations must have exactly one response message or an error.

https://github.com/grpc/grpc-java/issues/2785#issuecomment-286504286

**Comment by krakowski** [comment]
Hi Ryan,

thanks for the fast response! :blush: 

You are right, the grpc project includes a guard for this case within [`ServerCallImpl`](https://github.com/grpc/grpc-java/blob/e5bd7f282c45a7e90fdb9a9b6939b6ada6f8e31a/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L213-L216). Basically, it returns `Status.INTERNAL` if no message was sent.

```java
if (status.isOk() && method.getType().serverSendsOneMessage() && !messageSent) {
  internalClose(Status.INTERNAL.withDescription(MISSING_RESPONSE));
  return;
}
```

I think adding `responseObserver::onCompleted` at both locations ([`ServerCalls::oneToOne`](https://github.com/salesforce/reactive-grpc/blob/2b571218655674450ddd0b45af38b5bb0afd0915/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ServerCalls.java#L41-L50) and [`ServerCalls::manyToOne`](https://github.com/salesforce/reactive-grpc/blob/2b571218655674450ddd0b45af38b5bb0afd0915/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ServerCalls.java#L86-L101))  should suffice since grpc will handle the error . What do you think?

**Comment by rmichela** [comment]
Yes. I think moving the `responseObserver.onCompleted()` line to `rxResponse`'s `completeConsumer` will work.

The fix should also apply to RxJava.

**Comment by rmichela** [comment]
Yes. I think moving the `responseObserver.onCompleted()` line to `rxResponse`'s `completeConsumer` will work.

The fix should also apply to RxJava.

**Comment by krakowski** [comment]
I added the `completeConsumer` at both locations and extended your integration test to cover this special case. I tried to reproduce this bug using RxJava, but there doesn't seem to be a concept of empty [`Single`](http://reactivex.io/RxJava/javadoc/io/reactivex/Single.html)s. They can only complete with a value or an error.

**Comment by rmichela** [comment]
> They can only complete with a value or an error.

That makes sense.
