### ISSUE TITLE
Kotlin demo

### ISSUE THREAD

**Issue by cbornet** [salesforce/reactive-grpc#19]
I had some fun converting one of the demo to Kotlin.
I think it would be nice to use Kotlin the Reactor demo since the code generated is perfectly compatible.

@rmichela WDYT ?

**Comment by rmichela** [comment]
Kotlin would be fun. 😁 

I think it should be its own demo, in addition to the others. I don't want to lump too many disparate technologies into a single demo, otherwise the demo will lose its focus.

Do Kotlin and Java play nicely in the same IDE?

**Comment by cbornet** [comment]
> I think it should be its own demo, in addition to the others. I don't want to lump too many disparate technologies into a single demo, otherwise the demo will lose its focus.

My idea was to convert the full ReactorChat demo to Kotlin. I can also create a ReactorChat-Kotlin folder.

> Do Kotlin and Java play nicely in the same IDE?

I use IDEA and it works perfectly. I don't know for the other IDEs.

**Comment by cbornet** [comment]
Note that the stub and generated Reactor-gRPC code stays in JAVA. It's only the implementation code in the demo which is in Kotlin (Kotlin has 100% compatibility with JAVA code)

**Comment by rmichela** [comment]
Does Kotlin have any special relationship that makes it a valuable additional demo? 

If not, it sound like the Kotlin part is just for show (and because we can 😜 ). In that case, it makes sense to create a separate `ReactorChat-Kotlin` demo. That way the java-centric demos still show how vanilla java works.

**Comment by cbornet** [comment]
Yes Kotlin is for the show and because it’s a really nice language 😄
