### ISSUE TITLE
reactor-grpc-1.0.0.jar contains guava classes

### ISSUE THREAD

**Issue by neilswingler** [salesforce/reactive-grpc#191]
The 1.0.0 release of reactive-grpc clashes with guava 28 because the maven published reactor-grpc jar file actually contains the guava classes. Compare the size of 0.10.0 (4K) Vs 1.0.0 (6.7M)

**Comment by rmichela** [comment]
Help me understand how shading Guava into the `reactor-grpc` code generator is causing you a problem. 

The `reactor-grpc` jar is invoked by the protoc compiler as a separate `java -jar` process and runs in its own short-lived JVM. How is its contents clashing with your classpath? Are you embedding the `reactor-grpc` binary into your project as direct dependency? If so, why?

To test, I tried adding Guava 28.0-jre as a dependency to the `reactor-grpc-test` module and didn't see any classpath conflicts. I also verified that `reactor-grpc-stub` is not dragging along any shaded resources.

**Comment by neilswingler** [comment]
Aha I see. I must be adding it to the classpath. I will fix it on Monday. I guess I did not read the docs closely enough and only hit an issue upgrading to 1.0.0. The name of the reactor-grpc module does not suggest it's just a compiler plugin. Thanks for the fast response.

**Comment by rmichela** [comment]
Here's the docs for reference. https://github.com/salesforce/reactive-grpc/tree/master/reactor#installation

Do they need improvement? If they aren't clear I'd love to know. 😁

**Comment by neilswingler** [comment]
Confirmed that it was solved by removing the protoc plugin from the module dependencies. Maybe maven snippets of the protoc and runtime dependencies would help but I feel like itś more down to me not reading the documentation properly :)
