### ISSUE TITLE
Support of gRPC version 1.23.0

### ISSUE THREAD

**Issue by molokoka** [salesforce/reactive-grpc#192]
Sorry guys, are there any plans to support fresh version of gRPC and protobufs?

We are trying to use opencensus to collect metrics server and we have some problems with reactive-grpc using 1.19.0.

Thank you for help!

**Comment by rmichela** [comment]
The gRPC stub APIs are supposed to be backwards compatible. What specific problem are you having?

**Comment by molokoka** [comment]
You were right, it is something wrong with my config. I've found working example of project here: https://github.com/census-instrumentation/opencensus-java/tree/master/examples
