### ISSUE TITLE
RxJava 3

### ISSUE THREAD

**Issue by rmichela** [salesforce/reactive-grpc#202]
Please vote this issue up if you need RxJava3 support

**Comment by SuperJugy** [comment]
Any ETA on RxJava3 support?

**Comment by rmichela** [comment]
Haven't started it yet. But it seems there is some interest 😁

**Comment by AndreasLarssons** [comment]
I made an upgrade for myself that does compile all files to RxJava3 and also uses RxJava3 for all internal files. Also upgraded to Java 11. 

The main issue I had was that TestSubsriber has changed a lot of the methods on it so the had to change all tests and remove some asserts that were no longer available. I also could not figure out how to do the
StreamObserverAndPublisherTest.multithreadingFussedTest() with the new TestSubscriber so I left that one Ignored for now.

**Comment by rmichela** [comment]
Can you start a PR with RxJava3? @OlegDokuka might be able to help you with the fusing code. He knows way more about that than I do.

**Comment by AndreasLarssons** [comment]
PR submitted https://github.com/salesforce/reactive-grpc/pull/216

**Comment by scottslewis** [comment]
For everyone's info:  the rx java3 supported originally submitted by AndreasLarsons has been merged into master in pr #246 .

**Comment by rmichela** [comment]
Released in [1.2.0](https://github.com/salesforce/reactive-grpc/releases/tag/v1.2.0)
