### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by rmichela** [salesforce/reactive-grpc#21]
Add support for the [Google protobuf gradle plugin](https://github.com/google/protobuf-gradle-plugin).

See: https://github.com/google/protobuf-gradle-plugin/issues/168

**Comment by cbornet** [comment]
But for this to work, don't we need the jar to be executable ?

**Comment by rmichela** [comment]
Notes:
* https://github.com/google/protobuf-gradle-plugin/issues/31#issuecomment-315907690
* https://skife.org/java/unix/2011/06/20/really_executable_jars.html

**Comment by rmichela** [comment]
Executable jars are _possible_ 😉

**Comment by cbornet** [comment]
Of course it's possible 😄 . Spring Boot does it for instance.
The hard part is to publish an executable for each platform (Windows, Linux, 32/64 bits, ...).

**Comment by rmichela** [comment]
Based on the linked article, we only have to publish one artifact for linux-like operating systems. Bash and the existing platform-specific Java installation will take care of the rest.

Windows, OTOH, is a different story.

**Comment by cbornet** [comment]
For Windows, the maven protobuf plugin uses [winrun4j](http://winrun4j.sourceforge.net/)

**Comment by cbornet** [comment]
Code [here](https://github.com/xolstice/protobuf-maven-plugin/blob/protobuf-maven-plugin-0.5.1/src/main/java/org/xolstice/maven/plugin/protobuf/ProtocPluginAssembler.java#L123)

**Comment by rmichela** [comment]
So far I've got the `spring-boot-maven-plugin` generating self-contained, self-executing jars that work with with the `protobuf-gradle-plugin`. End-to-end tests work for Rx and Reactor! 🎉 

This technique only works for Linux-like operating systems, which is enough to start. I have not yet verified that code signing works correctly with the spring boot packaging format.

**Comment by rmichela** [comment]
Self executing spring boot jars work by prepending a [launcher bash script](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script) to the front of the jar's zip content. This is [allowed](https://en.wikipedia.org/wiki/Zip_(file_format)#Combination_with_other_file_formats) by the [standard](https://www.loc.gov/preservation/digital/formats/digformatspecs/APPNOTE%2820120901%29_Version_6.3.3.txt).

In theory, we could embed a cross-compiled golang launcher, instead of a bash script in each .jar, allowing for uniform support for linux and windows operating systems. Golang's [exec function](https://gobyexample.com/execing-processes) would be useful here.

**Comment by jebbench** [comment]
We've got this running under Pants by building an uber jar and then creating a shell script that just calls it - we point Protoc at the shell script which in turn calls the jar.

```
#!/usr/bin/env bash

java -jar build-support/protoc/rxgrpc-0.7.0.jar < /dev/stdin
```

Obviously isn't pretty and only works where bash is available but I don't imagine it would be hard to put together a Powershell equivalent.

**Comment by cbornet** [comment]
Yes.
A possibility is also to include the runtime : https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by rmichela** [comment]
@jebbench I've got the build producing a `-jdk8.jar` artifact compatible with the `:jdk8@jar` notation supported by the protoc-gradle-plugin. It embeds a similar script to yours as a prefix to the plugin's .jar file.

As you pointed out, this solution is *nix centric. Support for executing scripts as programs using `#!/...` notation is [generally consistent](https://www.in-ulm.de/~mascheck/various/shebang/), but [not standardized](https://stackoverflow.com/a/37295297). Windows has no native #! support, but [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) does. 

I think the script-prefixed-jar solution gets us most of the way there for support.

| OS | Maven | Gradle |
| :--- | :---: | :---: |
| *nix |  ✅  |  ✅  |
| MacOS |  ✅  |  ✅  |
| Windows |  ✅  |  Partial  |

Full support for windows would require the protoc-gradle-plugin to embed an executable launcher like winrun4j.

**Comment by rmichela** [comment]
I've merged #22 . Subsequent changes can come in separate PRs.

**Comment by nevi-me** [comment]
Hello :wave:

I'm the user who asked about this on the gRPC mailing list. I'll try out the plugin when Gradle support's landed for Windows. I develop in Windows but deploy to Linux :)

**Comment by cbornet** [comment]
@nevi-me as a workaround, you can call the maven-wrapper from a gradle task. See [here](https://github.com/cbornet/generator-jhipster-grpc/blob/v0.14.1/generators/app/templates/_grpc.gradle) for an example. A bit ugly but it works.
