### ISSUE TITLE
rxgrpc-1.0.0-linux-s390_64.exe is not available

### ISSUE THREAD

**Issue by rudolpho1** [salesforce/reactive-grpc#210]
Hi, first I would like to mention that I really like the work you did!! Now, here is the issue I have: For a project where I am using rxgrpc I have the requirement to compile it on s390 architecture (an IBM z-System). Unfortunately this does not work, because the plugin exe is only available for linux-x86_64 but not for linux_s390_64. I had the same problem with protoc and the grpc plugin, but these two projects I could easily recompile on s390. For rxgrpc I don't know how to do that. Could you help me with that? Thanks a lot!

**Comment by rmichela** [comment]
Are you using Maven or Gradle as your build system? For Maven, the plugin is natively invoked by the maven-protobuf-plugin as a java class. 

On gradle, the gradle-protobuf-plugin must shell out to an executable. In that case, the jar is packaged with Canteen, which makes it self-executing using a golang stub. You will first need to cross compile Canteen for your system, then use that to package reactive-grpc. https://github.com/salesforce/grpc-java-contrib/tree/master/canteen
