### ISSUE TITLE
Don't break the chain [Question]

### ISSUE THREAD

**Issue by Dimezis** [salesforce/reactive-grpc#211]
Hey, I'm reading this doc https://github.com/salesforce/reactive-grpc/blob/be8b74077cae5bbbe5ad360dbdcf37eb3f8b2f9b/rx-java/README.md

and trying to understand why the `compose/as` operators are preferable to a direct invocation.
Why exactly should I prefer this
`singleRequest.compose(stub::sayHello)`
to something like this
`stub.sayHello(singleRequest)`?
What are the consequences of doing it this way or another? 

Also, should I follow the same principle on the server and always chain from the `request` stream? Does it also require using some specific operators for chaining?

Could you please clarify it in Readme?

**Comment by rmichela** [comment]
Using `compose/as` is less immediately useful when doing simple unary RPC invocations. It really comes into play when you want a service call to be a middle step in a much longer reactive change. 

For example (pseudocode) `ClickEventSource -> debounce(1s) -> map(event to Request) -> compose(stub::boxService) -> map(Response to coordinates) -> subscribe(drawBoxOnScreen(coordinate))`

**Comment by Dimezis** [comment]
So it's just a matter of convenience, but not some functional requirement?
