### ISSUE TITLE
reactor fails to generate gRPC stub in latest version

### ISSUE THREAD

**Issue by dimi-nk** [salesforce/reactive-grpc#213]
Hey,

|gRPC|protoc|reactive|
|---|---|---|
|1.29.0|3.12.2|1.0.1|

I just updated to the latest gRPC/protoc/reactive-grpc and the compiler fails with the following message:

```bash
AdminServiceGrpc.java:[76,29] error: cannot find symbol
  symbol:   class StubFactory
  location: class AbstractStub
```

And the generated code:

```java
  public static AdminServiceBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    io.grpc.stub.AbstractStub.StubFactory<AdminServiceBlockingStub> factory =
      new io.grpc.stub.AbstractStub.StubFactory<AdminServiceBlockingStub>() {
        @java.lang.Override
        public AdminServiceBlockingStub newStub(io.grpc.Channel channel, io.grpc.CallOptions callOptions) {
          return new AdminServiceBlockingStub(channel, callOptions);
        }
      };
    return AdminServiceBlockingStub.newStub(factory, channel);
  }
```

I'm using this maven plugin to generate the stubs:

```xml
  <properties>
    <protobuf.version>3.12.2</protobuf.version>
    <grpc.version>1.29.0</grpc.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.6.1</version>
        <extensions>true</extensions>
        <configuration>
          <pluginId>grpc-java</pluginId>
          <protocArtifact>
            com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}
          </protocArtifact>
          <pluginArtifact>
            io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}
          </pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

I also tried your protoc [plugin](https://github.com/salesforce/reactive-grpc/tree/master/reactor#maven), but I get the same issues.

I cannot find a table of version mapping, so I'm not sure if the versions do not match or the maven plugin doesn't work correctly or something else. Any help is appreciated.

**Comment by rmichela** [comment]
Which versions were working before? Did you upgrade everything all at once, or step by step?

**Comment by cbornet** [comment]
Strange because io.grpc.stub.AbstractStub.StubFactory seems to still exist : https://github.com/grpc/grpc-java/blob/049b12818b87aae4df9a92fbe35540b92a653dee/stub/src/main/java/io/grpc/stub/AbstractStub.java#L258
Are you sure you pull the `grpc-stub` dependency ?

**Comment by dimi-nk** [comment]
@cbornet what seems to be missing is the `StubFacotry` inner class from `AbstractStub`

**Comment by dimi-nk** [comment]
@cbornet it looks like this is being resolved wrong

![image](https://user-images.githubusercontent.com/2273840/84159698-42f51c00-aa65-11ea-851f-5ef6b947ddda.png)

**Comment by cbornet** [comment]
What version of `io.grpc:grpc-stub` is resolved ?

**Comment by dimi-nk** [comment]
`1.29.0`

**Comment by dimi-nk** [comment]
However, the compiler seems to be picking up the `AbstractStub` class bundled inside `com.salesforce.servicelibs:reactor-grpc-stub:1.0.1` as shown above.

**Comment by dimi-nk** [comment]
@rmichela 

I've updated them all at ones since I expected the latest versions of all three would play together a bit better.

|gRPC|protoc|reactive|
|---|---|---|
|1.25.0|3.11.1|0.9.0|

**Comment by dimi-nk** [comment]
Updating gRPC and protoc to the latest while leaving `reactor-grpc` to `0.9.0` seems to work.

**Comment by dimi-nk** [comment]
So, the build works up to `reactor-grpc`&`reactor-grpc-stub` `0.10.0`. The moment I pop that to `1.0.0`, the dependency brings some `io.grpc` classes bundled with it and breaks the compilation. I looked at the commits between `0.10.0` and `1.0.0` and it might be the introduction of Canteen.

**Comment by cbornet** [comment]
`reactor-grpc-stub` doesn't bundle `grpc-stub`. It's `reactor-grpc` which bundles it but it's only used during code generation.
I don't reproduce your issue with the reactor-chat demo. Could you give your full pom.xml ?

**Comment by cbornet** [comment]
Ensure that you don't have `reactor-grpc` in your dependencies. It's meant to be used only in the protocPlugins section.

**Comment by dimi-nk** [comment]
@cbornet I'm not saying `reactor-grpc-stub` is, but `reactor-grpc` bring all the dependencies as part of its classpath. Like I've shown in the screenshot above, `reactor-grpc` introduces the class `io.grpc.stub.AbstractStub` and the maven compiler is trying to use that rather than the class brought by `grpc-stub`. The reactor's `AbstractStub` is missing the `StubFactory` inner class.

**Comment by dimi-nk** [comment]
> Ensure that you don't have `reactor-grpc` in your dependencies. It's meant to be used only in the protocPlugins section.

AH, maybe that's the reason then.

**Comment by dimi-nk** [comment]
My bad then missed that in the documentation! Sorry for the spam, I thought I was on to something 😂. Thanks for the help.

**Comment by cbornet** [comment]
@rmichela maybe we could shade `io.grpc` packages in `reactor-grpc` so that accidentally pulling it doesn't break everything ?
