### ISSUE TITLE
Is Java 7 supported?

### ISSUE THREAD

**Issue by jibs239** [salesforce/reactive-grpc#215]
The documentation mentions that the generated code targets Java 6 and above. 
https://github.com/salesforce/reactive-grpc#android-support

However, I observe that the generated code uses method references in a few places. Also, Maven build generates the below error.
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/salesforce/rxgrpc/RxGrpcGenerator : Unsupported major.minor version 52.0

Can you please confirm and update the documentation with specific, accurate Java version support?

**Comment by rmichela** [comment]
It's increasingly difficult to support 10 year old JDKs. Starting with 1.1.0 >= java 8 will be required.
