### ISSUE TITLE
reactor-grpc-1.0.1-linux-aarch_64.exe availability for aarch64

### ISSUE THREAD

**Issue by odidev** [salesforce/reactive-grpc#229]
I am working to make [Armeria](https://github.com/line/armeria) available for aarch64 platform.

Armeria build on aarch64 platform is failing with below error, **in seek of aarch64 specific binary availability at [maven repo](https://repo1.maven.org/maven2/com/salesforce/servicelibs/reactor-grpc/1.0.1/)**:
```
> Task :examples:grpc-reactor:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:grpc-reactor:generateProto'.
> Could not resolve all files for configuration ':examples:grpc-reactor:protobufToolsLocator_reactorGrpc'.
   > Could not find reactor-grpc-1.0.1-linux-aarch_64.exe (com.salesforce.servicelibs:reactor-grpc:1.0.1).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/salesforce/servicelibs/reactor-grpc/1.0.1/reactor-grpc-1.0.1-linux-aarch_64.exe
```

Please share the plan to release the same for aarch64. Also, if there is any way to make it available by building locally for the time please let us know.

**Comment by rmichela** [comment]
Fixed in v1.1.0
