### ISSUE TITLE
Support optional feature

### ISSUE THREAD

**Issue by Tiller** [salesforce/reactive-grpc#230]
Hello,
With protobuf 3.12.x came the experimental feature of the optional fields. The general availability was targeted to 3.13.x but has been postponed to (hopefully) the next release.
I tried to use the experimental feature, but I can't get it to work with reactive-grpc, I get the following message:

> file.apg is a proto3 file that contains optional fields, but code generator protoc-gen-reactor hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional

Could you consider supporting this feature? Thanks

https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#signaling-that-your-code-generator-supports-proto3-optional

**Comment by captainhorsepower** [comment]
UPD. Optional is no longer an experimental feature, but plugin still needs to signal that it supports optional fields.

**Comment by rmichela** [comment]
Implemented in 1.1.0

**Comment by Dimezis** [comment]
May I ask when 1.1.0 will be released?

**Comment by rmichela** [comment]
Released in 1.1.0
