### ISSUE TITLE
Java execution error: exec: "java": executable file not found in %PATH%

### ISSUE THREAD

**Issue by iamceph** [salesforce/reactive-grpc#232]
Hey there, I got a problem with generating protofiles for Reactor.

I am using Gradle 6.7.1 with latest grpc gradle plugin (0.18.4) and with latest gRPC (1.33.1).
It seems that I just cannot create Reactor files due to this error. Any help would be appreciated :)

`Execution failed for task ':protofiles:generateProto'.
> protoc: stdout: . stderr: 2020/11/29 13:16:21 Java execution error: exec: "java": executable file not found in %PATH%
  --reactor_out: protoc-gen-reactor: Plugin failed with status code 1.`

**Comment by rmichela** [comment]
I think this is fixed in the (unreleased) #225.
