### ISSUE TITLE
UnsupportedOperationException thrown in the generated stub with Java 17

### ISSUE THREAD

**Issue by ivy-kl-chan** [salesforce/reactive-grpc#299]
Hello!
I'm getting and UnsupportedOperationException when running ClientCalls.manytoMany with the stub generated with both rx3Java and rxJava.
I'm using Java 17. What would be the possible cause of the problem?

**Comment by rmichela** [comment]
Does the problem go away when you use an earlier version of the JRE?

**Comment by rmichela** [comment]
I've run the entire regression suite on Java 17, to include compiling specifically for 17, and couldn't reproduce this bug. If it happens again, please include more details about the exception, and if possible, a reproducing case.
