### ISSUE TITLE
Subscription Should be Cancelled on Interceptor Close

### ISSUE THREAD

**Issue by jGleitz** [salesforce/reactive-grpc#304]
When an interceptor closes the call, the reactive subscription is _not_ cancelled. This means that any resource allocated for a call are not removed, either, and effectively leak.

To circumvent this, I think the library should listen `ServerCall.Listener.onComplete` and `ServerCall.Listener.onCancel`, and cancel its subscription of the reactive sequence in reaction to it (if the sequence hasn’t completed yet).

**Comment by jGleitz** [comment]
Here’s a test case reproducing the issue: #305

**Comment by jGleitz** [comment]
@rmichela thank you for reviewing & merging so quickly! Do you have the chance to publish a release? We’d like to profit from the changes as soon as possible.

**Comment by rmichela** [comment]
I lost my publish rights when I left Salesforce. Still working on getting someone to fill that role.
