### ISSUE TITLE
Question: how can Spring reactive-grpc support credentials on server

### ISSUE THREAD

**Issue by travispeloton** [salesforce/reactive-grpc#323]
**Question:**

How can Spring reactive-grpc support credentials on the server?

We would like to authenticate clients and are not clear on what our options are. Thanks!

**Comment by cbornet** [comment]
I did something like that some time ago using a ServerInterceptor. See https://github.com/cbornet/jhipster-grpc-sample-app/blob/master/src/main/java/io/github/jhipster/grpcsample/grpc/AuthenticationInterceptor.java
Hope that helps.

**Comment by travispeloton** [comment]
thanks for the help!
