### ISSUE TITLE
Best way to retry on a reactive-grpc stream after an error

### ISSUE THREAD

**Issue by matgabriel** [salesforce/reactive-grpc#36]
Hello,

I have a pretty simple use case: a gRPC service with a method taking a stream as argument and returning a stream.

I would like to resubscribe, if for example the remote server goes down.
On a normal stream if would just use retry (with some delay) to resubscribe on error:

`Flux<ResultType> resulfFlux =  myService.myMethod(sourceStream).retry();`

However it is not possible with reactive-grpc:

```
Exception in thread "grpc-default-executor-0" java.lang.NullPointerException: You cannot directly subscribe to a gRPC service multiple times concurrently. Use Flowable.share() instead.
	at com.salesforce.reactorgrpc.stub.SubscribeOnlyOnceLifter$1.onSubscribe(SubscribeOnlyOnceLifter.java:32)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onSubscribe(FluxPublishOn.java:202)
```

(btw, this should be Flux.share() instead of Flowable.share())

**Do you have any elegant way to achieve this retry on error?**

A naive approach with recursion to resume the stream will of course result in a stackoverflow after some time:

```
Flux<ResultType> getResultStream(Flux<SourceType> sourceStream){
        return myService.myMethod(sourceStream)
                .onErrorResume(err -> Flux.defer(() -> getResultStream(sourceStream)))
                
}
```

The only partially working approach I found is to chain it with thenMany to avoid a stackoverflow, but it is then not possible to subscribe to the result stream since thenMany waits for the completion of the previous stream...

```
Flux<ResultType> getResultStream(Flux<SourceType> sourceStream){
        return myService.myMethod(sourceStream)
                 .onErrorResume(err -> Flux.empty())
                 .thenMany(Flux.defer(() -> getResultStream(sourceStream)))    
}
```

**Comment by rmichela** [comment]
Hmm... I'll have to do some digging to come up with a more elegant solution. @cbornet Any ideas from your end?

**Comment by matgabriel** [comment]
I found another solution that is a more elegant: we can simply wrap it in another Flux:
```

Flux.create(sink -> {
                    myService.myMethod(sourceStream)
                            .subscribe(sink::next, sink::error, sink::complete);
                });
```

this way the gRPC stream is recreated by the retry.

**Comment by rmichela** [comment]
Composability FTW! 

Is there a way to codify this pattern in a custom operator? Does even make sense to?

RxJava supports [custom operators and transformers](https://github.com/ReactiveX/RxJava/wiki/Implementing-Your-Own-Operators) that can implement patterns like this. Does Reactor support something similar? (@cbornet knows Reactor a lot better than I do.)

**Comment by cbornet** [comment]
@rmichela yes Reactor has custom operators and transform. Actually Reactor is a rewrite of RxJava so most of RxJava concepts are available. See an example of transformation [here](https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ClientCalls.java#L48). So if we do something for one of the lib, it should be easy to do it for the other one.

**Comment by matgabriel** [comment]
One simple way to reuse it is to wrap it in a class extending Flux (or Flowable):

```
public class GrpcRetryFlux<T> extends Flux<T> {
    private static final Logger LOGGER = LoggerFactory.getLogger(GrpcRetryFlux.class);
    private final Flux<T> retryFlux;

    public GrpcRetryFlux(Supplier<Flux<T>> fluxSupplier) {
        this.retryFlux = Flux.<T>create(sink -> fluxSupplier.get().subscribe(sink::next, sink::error, sink::complete))
                        .retryWhen(attempts -> attempts.doOnNext(err -> LOGGER.warn("Received error", err)).flatMap(i -> Mono.delay(ofMillis(500))));
    }

    @Override
    public void subscribe(CoreSubscriber<? super T> actual) {
        retryFlux.subscribe(actual);
    }
}
```

Then we can use it like that: 

`Flux<ResultType> resulfFlux = new GrpcRetryFlux<>(() -> myService.myMethod(sourceFlux));`

I am not sure if it would be worth including something like that in the generated code.
In most of my use cases I want to try to reconnect to the streams, but some people might have different expectations.

**Comment by rmichela** [comment]
I was thinking about retry/reconnect last night. How it's implemented is very application specific.

Your `Flux.create(sink -> ...` solution is essentially a one-liner. I'm thinking it may be better as a documentation note instead of a library class.

**Comment by matgabriel** [comment]
Agreed, this is simple enough to let the user choose.

**Comment by bsideup** [comment]
@matgabriel 
```java
Flux.defer(() -> myService.myMethod(sourceStream))
```

**Comment by matgabriel** [comment]
@bsideup
Thanks, using defer is a better solution since it handles the cancellation of the source Flux automatically.
In my tests it also seems to handle error scenarios better.

**Comment by cbornet** [comment]
@matgabriel @bsideup would of you do a PR to update the demo ?

**Comment by matgabriel** [comment]
Done:
https://github.com/salesforce/reactive-grpc/pull/49
