### ISSUE TITLE
Lambda expressions break Android

### ISSUE THREAD

**Issue by OlegZhilo** [salesforce/reactive-grpc#37]
Could u explain? how to add u library to Android Studio?

All classes have generated. But after call stub I have a crash.
![crash](https://user-images.githubusercontent.com/8090222/35051331-0e990a9e-fbb6-11e7-9c73-045dd8b4c376.png)
Multidex is enabled. MinSdk 21.
![grpc](https://user-images.githubusercontent.com/8090222/35051484-5cba050c-fbb6-11e7-9436-604931b8db56.png)

**Comment by rmichela** [comment]
Thanks for the update. Android development only supports [language features up to JDK 7](https://stackoverflow.com/questions/20480090/does-android-support-jdk-6-or-7).

Reactive-Grpc uses lambda expressions from JDK 8. I'll have to replace the lambda expressions with classes to make Reactive-Grpc work on Android. :confused: Thank you for bringing this to my attention. Unfortunately, there is no quick fix.

**Comment by rmichela** [comment]
It looks like the latest Android Studio supports some Java8 features. Perhaps this can help? https://developer.android.com/studio/write/java8-support.html

**Comment by OlegZhilo** [comment]
I have build project on macOs and everything is fine. But on my work place I have a pc + ubuntu, and app that build on ubuntu machine get a crash on call to server. That's very strange behavior....

**Comment by OlegZhilo** [comment]
I have found answer.... 
In com.salesforce.rxgrpc.stub.ClientCalls you are using 
import java.util.function.BiConsumer;
import java.util.function.Function;

but android support it on api 24+
On Android Nougat and Oreo works perfect, but on <24 crash....

**Comment by rmichela** [comment]
Thanks for the update. I'll have to make some updates so the stubs compile for older versions of Android.

**Comment by OlegZhilo** [comment]
I'm sorry for my perseverance. When do you plan update it?

**Comment by rmichela** [comment]
I don't have an ETA. If you need this faster, I'm happy look at a PR. :wink:

**Comment by OlegZhilo** [comment]
ok, thanks))

**Comment by rmichela** [comment]
I've opened a PR. Can you test it before I merge? I don't have an Android development environment to use.

**Comment by OlegZhilo** [comment]
Will look into it immediately)))

**Comment by OlegZhilo** [comment]
How can I painless get dependency in my project?
Sorry for my noob question.

**Comment by rmichela** [comment]
I've downgraded the language level for RxGrpc to 1.6 to support RxJava on Android. @OlegZhilo has verified the fix.

I will ship 0.7.3 no later than the end of January. Release is currently blocked by #40.

**Comment by OlegZhilo** [comment]
@rmichela Thanks so much.
