### ISSUE TITLE
Depracated API in grpc 1.9.0

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [salesforce/reactive-grpc#41]
The "XxxServiceGrpc.METHOD_YYY" static fields have been deprecated in the recent grpc releases and replaced with methods. The change is explained here:
https://github.com/grpc/grpc-java/issues/1901

To reproduce, update grpc to 1.9.0 and generate stubs for any service. The generated code will produce deprecation warnings during compilation.

**Comment by cbornet** [comment]
Indeed ! Would you do a PR for this ?
