### ISSUE TITLE
Unary call blocks indefinitely if the server completes empty

### ISSUE THREAD

**Issue by javier-godoy** [salesforce/reactive-grpc#74]
Create a unary RPC. On the server, have it immediately call `responseObserver.onCompleted()` with no previous `onNext()`. With an io.grpc client call, this RPC [throws an INTERNAL error](https://github.com/grpc/grpc-java/blob/c9b02db276403db4794c6e5ffc78b46889cd4ce8/stub/src/main/java/io/grpc/stub/ClientCalls.java#L450) (see https://github.com/grpc/grpc-java/issues/2785) because one-to-one calls must either fail or have a message. With reactor-grpc (0.8.1), the returned `Mono` neither completes nor fails, causing it to block indefinitely.
	
Service:
```
rpc test (google.protobuf.Empty) returns (google.protobuf.UInt64Value);
```

Server: 
```
public void test(UInt64Value request, StreamObserver<UInt64Value> responseObserver) {
   ServerCalls.oneToOne(request, responseObserver, x->Mono.empty());
}
```
	
Client:
```
Mono<Empty> request = Mono.just(Empty.getDefaultInstance());
Mono<UInt64Value> response = ClientCalls.oneToOne(request stub::test);
System.out.println(response.blockOptional().isPresent());
```

Workaround: define the RPC as server-streaming (one-to-many) and call `flux.singleOrEmpty().blockOptional()`, which kind of defeats the purpose of `Mono`.
 (I'm not sure if the one-to-one case should fail or return an empty `Mono`, but at least it *should not block*).

**Comment by rmichela** [comment]
That's an interesting failure condition. I'll look into it.

**Comment by rmichela** [comment]
@javier-godoy I've added additional unit tests in #76. I believe they cover your case, and they pass, so this problem should be fixed. Please re-open this issue with further details if I misunderstood your conditions.
