### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by OlegZhilo** [salesforce/reactive-grpc#79]
How to set timeout for requests?
Grpc has method for that - withDeadlineAfter(). but I can't apply it with your library.

**Comment by dadadom** [comment]
Have you tried with the latest version, 0.8.1? In it, all stubs extend `AbstractStub` which gives them e.g. the `withDeadlineAfter()` method: https://github.com/salesforce/reactive-grpc/releases/tag/v0.8.1
An example of the usage can be found here: https://github.com/salesforce/reactive-grpc/blob/1230b6a0c834102cce5de466d26974fd5eba8b2a/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/AbstractStubTest.java

**Comment by OlegZhilo** [comment]
@dadadom Oh! Nice, Time to use 0.8.1 version. Thanks so much. I will try it.

**Comment by OlegZhilo** [comment]
use 0.8.1
