### ISSUE TITLE
Can I use this with SBT ?

### ISSUE THREAD

**Issue by unoexperto** [salesforce/reactive-grpc#94]
Hey guys,

Is it possible to use `RxGrpcGenerator` with SBT ?

**Comment by rmichela** [comment]
I believe you can, but I am by no means an SBT expert. 😁 

It looks [sbt-protoc](https://github.com/thesamet/sbt-protoc) supports [custom java code generators](https://github.com/thesamet/sbt-protoc/tree/master/examples/custom-gen). Since reactive-grpc is a custom java code generator, it _should_ work.

**Comment by rmichela** [comment]
@unoexperto Does sbt-protoc solve your problem?

**Comment by unoexperto** [comment]
@rmichela 

Looks like I'm missing something and I couldn't figure out what in 2 hours. Could you please take a look ?

https://github.com/unoexperto/test-rxgrpcgenerator

Generated by your plugin `RxGreeterGrpc.java` is referencing `com.example.protos.GreeterGrpc` class which is not available. I wonder if I need to call other generator before `RxGrpcGenerator`.

What do you think ?

**Comment by unoexperto** [comment]
After wasting 4 hours I came to conclusion that it all boils down to making `protoc` use `protoc-gen-grpc-java` plugin which I have no idea how to do in this context. If you can make it work I'll deeply appreciate it.

**Comment by rmichela** [comment]
I have no meaningful experience with SBT and Scala. Please re-open if there is anything reactive-grpc can improve to make working with SBT easier.

**Comment by cbornet** [comment]
@unoexperto if you manage to make it work, don't hesitate to do a PR to enhance the doc as it might interest others.
