### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by geniusayush** [salesforce/reactive-grpc#97]
Hi, we are considering to use this library in our grpc application. Wanted to know about the current staus and if this is ready to be used in production?

**Comment by rmichela** [comment]
Great question. I encourage you to try it out. We haven't heavily adopted this library yet at Salesforce, but based on the few github issues I've seen, others are using reactive-grpc in production.

I say, do a spike and report your findings. Anything you find, even negative, will be great for moving the project forward.

**Comment by bsideup** [comment]
We use this library to implement a back-pressure aware [Kafka gRPC Gateway](http://github.com/bsideup/liiklus) (and connect to) in our 30+ micro-services in production. 

There were some issues at the beginning but now (especially with the latest 0.9.0 release) it works really well 👍 

Our use case is relying on the back-pressure a lot, and I can say that we haven't observed any major issues with it so far (and the minors were already reported & fixed)

**Comment by rmichela** [comment]
@bsideup We've just released 0.10.0-RC1 and would love your feedback.
